### PR TITLE
Notify next set of on-calls

### PR DESCRIPTION
**Pull request by chenbh**
- notifies every weekday at 4-5pm
- tries to find next day or next Monday if it's a Friday
- no idea what happens when it's a holiday/nobody scheduled for on-call (probably has the header but nobody in the contents)

### CODE REVIEW

**Comment by cirocosta** [comment]
Hey, I noticed that we're already notifying 🤔  

Did you end up deploying it without getting the code in, @chenbh ?

I guess that's enough validation that it works lol

cc @topherbullock

**Comment by cirocosta** [comment]
(adding to the description of the PR):

- the PR also includes communicating with `#concourse-wings`, which, btw, seems to be working pretty well 😁

**Comment by aegershman** [comment]
Apologies for creeping on this issue, but as an aside I'm curious how you all are using pagerduty or whatever your notification/alerting system is. Noticing you have a `PAGERDUTY_ESCALATION_POLICY` as a param in the `ci` flow, so am curious how you use pagerduty / how well it works for you all.

**Comment by chenbh** [comment]
@cirocosta oh yeah, it's pointing to my fork right

@aegershman 
The go code for this basically looks up the person who is on-call today from pagerduty, (tries to) map it to a slack user and generate a couple of slack messages using it.

1. We have a schedule set up in pagerduty that has 2 on-call members everyday
1. The pipeline triggers the go code every workday morning
1. The go code uses our token and escalation policy and looks up who's on call today (https://api-reference.pagerduty.com/#!/On-Calls/get_oncalls)
1. It also users our slack tokens and channel looks up the slack handles for our team members (https://api.slack.com/methods)
1. The go code parses all those and generate a message to be sent to our channels
1. We have a Slack app installed in our channels which is configured with an incoming webhook (https://api.slack.com/incoming-webhooks)
1. The pipeline uses the slack-resource and the message generated to send to the webhook

**Comment by aegershman** [comment]
right on, okay. Again, I'm really sorry for taking this a bit off-topic, I won't push anymore than this, but overall do you like this workflow / find working with pagerduty & pagerduty's APIs to be a decent experience?

**Comment by chenbh** [comment]
@aegershman hmmm, this workflow originally came along because there was some confusion regarding figuring out who would be on call every day.

Pagerduty does send email notifications the day before you're scheduled for on call, but some of the team found it easier to periodically check our slack channels rather than go through our backlog of emails. There's also the fact that we wanted to notify an entire channel instead of just the team and Pagerduty doesn't really do that nicely.

If you are talking about the technical details of working with the API, it was kinda confusing for me personally as under the "Documentation" section there were mentions of a `v1` and a `v2` REST API but at the same time there's a separate section about "REST API Reference"???

Once I figured out which one to use I gotta admit the ability to just provide my token and try out live requests from the documentation page itself was very nice.

**Comment by topherbullock** [comment]
Mergin' this in before forking this repo over to the `concourse` org, since it's deployed and working!

@chenbh one thing I'll clean up after merging is replacing [this func](https://github.com/chenbh/flight-attendant/blob/d733861a68bfcde424c618a39d3bbd2362e4ae40/main.go#L211-L219
) with `ioutil.Writefile`,  which is a functionally similar bit of Go's standard lib :  https://golang.org/src/io/ioutil/ioutil.go?s=2534:2602#L69. Won't let that block merging though!

**Pull request merged**
